version: "3.7"
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: steam-site-mssql
    volumes:
      - events_mssql:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1
      - MSSQL_PID=Developer
      - MSSQL_DB=events_service
      - MSSQL_USER=SA
      - MSSQL_PASSWORD=Password1
      - MSSQL_DB_AUDIT_LOG=events_service_audit_log

volumes:
  events_mssql: