export const Home = () => {
  return (
    <div className="main">
      <ul className="generic-list">
        <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, vero.</li>
        <li>Asperiores distinctio corporis voluptatem eligendi mollitia iure nam quo rem.</li>
        <li>Corrupti veniam at, similique ea molestias beatae ullam. Voluptate, illo.</li>
        <li>Ipsa, velit nihil! Magni fuga deleniti nostrum labore natus aut?</li>
        <li>Accusantium quasi aliquid quidem soluta sunt eveniet in illum praesentium!</li>
        <li>Eius perspiciatis iusto eaque cum repudiandae deleniti ullam cumque laboriosam?</li>
        <li>Accusamus commodi aperiam provident, earum sunt inventore eum. Eligendi, repellendus!</li>
        <li>Officiis consequuntur vitae qui nam corrupti perferendis consectetur esse deserunt!</li>
        <li>Dolores adipisci quibusdam totam, debitis placeat nemo hic culpa doloribus.</li>
        <li>Reprehenderit repellat deleniti eius id, repudiandae eos. Exercitationem, quo sapiente.</li>
        <li>At neque voluptatem dolores exercitationem quos, possimus accusantium impedit aperiam?</li>
        <li>Eum voluptates numquam dignissimos recusandae dolor nemo nostrum blanditiis odio!</li>
        <li>Id tenetur consequatur modi consectetur. Vitae rem nulla rerum nam?</li>
        <li>Nihil quidem amet labore architecto id officia? Ex, sed hic.</li>
        <li>Hic dicta quae incidunt quaerat porro illo at eligendi necessitatibus!</li>
        <li>Nostrum ullam ipsa fuga nobis sapiente ipsam aliquid assumenda distinctio.</li>
        <li>Fuga, accusamus libero ipsam dolores tempore illum laudantium soluta recusandae.</li>
        <li>Provident libero ipsa corporis sequi, illo iusto labore quam corrupti.</li>
        <li>Quis eum modi porro, mollitia laboriosam sunt iure quod natus.</li>
        <li>Sequi ea nemo vitae animi aliquid tenetur ratione incidunt consequuntur!</li>
        <li>Nulla iste expedita a eum enim. Enim voluptatem delectus qui.</li>
        <li>Ipsum, quibusdam sed eos nisi eaque ut id illum voluptas!</li>
        <li>Provident dicta saepe porro doloremque cumque dolorem, sunt itaque voluptatum!</li>
        <li>Facere dolorem itaque nam dolores culpa. Aspernatur enim odit deserunt!</li>
        <li>Illum excepturi suscipit culpa eaque neque delectus, a rerum. Nihil.</li>
        <li>Voluptas corrupti, optio dicta recusandae adipisci dolorum odio. Placeat, possimus.</li>
        <li>Quo cum ut vel unde laudantium, temporibus amet atque cupiditate?</li>
        <li>Cupiditate suscipit velit tempore libero ex, quisquam alias tenetur ratione!</li>
        <li>Neque dolorem doloribus nihil labore veritatis quod sapiente cupiditate asperiores.</li>
        <li>Reiciendis qui natus alias sunt ex nihil, pariatur exercitationem! Sunt?</li>
        <li>Praesentium laudantium maxime error suscipit inventore culpa numquam veniam fugiat.</li>
        <li>Eius officia beatae, in quasi debitis vitae minus voluptates deleniti!</li>
        <li>Veniam, fuga a sequi voluptate error repudiandae magnam minus consectetur.</li>
        <li>Ullam, eveniet harum rerum voluptas libero sapiente vitae debitis perferendis.</li>
        <li>Ab est dolorem mollitia ullam, quasi numquam accusamus natus quidem?</li>
        <li>Unde nostrum ipsam perspiciatis assumenda non consequatur delectus fugiat ex.</li>
        <li>Iste accusantium expedita ab iusto, tempore porro veritatis perspiciatis incidunt.</li>
        <li>Consequatur accusantium quas, animi iste sit id qui accusamus cum.</li>
        <li>Aliquid reiciendis ipsa itaque accusantium. Alias impedit omnis eveniet est.</li>
        <li>Recusandae magnam aut officiis aperiam inventore facilis, similique possimus odio.</li>
        <li>Iusto, dolor? Inventore rerum repellat quasi dolores vel, eaque suscipit.</li>
        <li>Dignissimos commodi nesciunt ducimus soluta, id voluptas doloribus cumque repellendus?</li>
        <li>Quidem accusamus officia eos quia quibusdam provident neque id nisi.</li>
        <li>Cupiditate dignissimos doloribus quibusdam? Minima necessitatibus ad ullam vel impedit!</li>
        <li>Vero quis numquam odit amet commodi beatae temporibus officia quidem?</li>
        <li>Tenetur facere consectetur autem ipsum vel voluptatum, veritatis magnam velit?</li>
        <li>Distinctio, iure ipsam. Cupiditate omnis at, deserunt rerum assumenda debitis?</li>
        <li>Quaerat eos odit nisi commodi necessitatibus ut culpa ullam doloremque!</li>
        <li>Aspernatur odio animi delectus voluptatum odit, laborum sapiente modi numquam!</li>
        <li>Dolor molestias obcaecati nostrum voluptatibus hic nemo quod, porro labore.</li>
        <li>Dolores consequatur, pariatur amet totam vel nesciunt autem quod sed.</li>
        <li>Rerum, at necessitatibus! Hic dolor porro atque ex deserunt inventore.</li>
        <li>Facere molestiae saepe quo possimus. Pariatur ipsum quas architecto eos?</li>
        <li>Fugiat reprehenderit iste alias animi eos delectus assumenda sed dolores!</li>
        <li>Accusamus expedita voluptatem id dolores possimus eveniet reiciendis tempore quo.</li>
        <li>Magnam eum similique asperiores iusto dolore exercitationem autem facilis sequi.</li>
        <li>In reiciendis soluta totam architecto laborum facere nemo neque animi.</li>
        <li>Inventore quae molestias eveniet ipsam dolore consequatur hic, laudantium quia.</li>
        <li>Incidunt sunt autem enim, error quaerat fugit. Ex, distinctio amet?</li>
        <li>Fugiat sint alias, obcaecati ducimus dolor impedit recusandae in laboriosam?</li>
        <li>Rerum in distinctio reprehenderit illum esse assumenda maiores aspernatur repellendus.</li>
        <li>Distinctio, sequi? Est, necessitatibus aperiam? Tempore velit maxime ipsa ratione!</li>
        <li>Nobis perferendis consequatur quia quos pariatur dolor aut vel est!</li>
        <li>Minima repellat sint expedita consectetur et exercitationem quaerat eius beatae!</li>
        <li>Deleniti quo alias quod hic culpa. Nostrum quisquam tenetur esse?</li>
        <li>Quia rerum, accusamus quos nisi aliquid animi rem doloribus distinctio?</li>
        <li>Hic iure tempora sequi incidunt, atque possimus vel sint nihil!</li>
        <li>Dolores vitae totam quibusdam. Ullam sequi expedita hic quisquam ipsum.</li>
        <li>Eaque voluptate a dolorum illo maiores libero nostrum consectetur porro!</li>
        <li>Odit quisquam accusantium enim. Asperiores libero tempore ipsam. Corporis, possimus.</li>
        <li>Impedit soluta beatae, numquam molestias reprehenderit corrupti velit dolorem ut.</li>
        <li>Minus tenetur quaerat nemo quod cumque distinctio totam suscipit quasi?</li>
        <li>Culpa eius, accusantium aliquam exercitationem repellendus ipsum numquam explicabo molestias?</li>
        <li>Sapiente provident totam inventore voluptatibus aliquam beatae, suscipit eos porro.</li>
        <li>Nam expedita quidem aspernatur sequi beatae provident dolore laudantium minus.</li>
        <li>Harum, repellat corrupti cumque quam mollitia nostrum provident pariatur. Commodi.</li>
        <li>Saepe asperiores, qui voluptatum animi aliquam ducimus assumenda ut dolor.</li>
        <li>Eaque ipsam consequuntur vel praesentium explicabo voluptatem, eum obcaecati quos.</li>
        <li>Nesciunt, at nobis optio doloribus numquam atque est excepturi mollitia?</li>
        <li>Perspiciatis quia nam ipsam, animi quibusdam aut tempora! Mollitia, facere!</li>
        <li>Id sequi ullam et autem sed. Ab ratione officia tempora.</li>
        <li>Nihil vero facere nemo! Illo optio laborum tempore rem facilis.</li>
        <li>Totam beatae ratione nulla culpa rem rerum quo dignissimos saepe!</li>
        <li>Dicta consequuntur doloremque tenetur ullam voluptatem ratione unde illum et.</li>
        <li>Modi rem totam vitae incidunt. Quisquam corporis earum repellendus aspernatur.</li>
        <li>Dolores culpa animi ipsum vel perferendis dicta voluptate praesentium harum.</li>
        <li>Animi consequatur alias eveniet voluptatibus laboriosam totam dolorum neque officiis.</li>
        <li>Officia exercitationem tenetur natus, quaerat soluta voluptates pariatur illum ducimus.</li>
        <li>Eos labore eveniet repellat, sapiente molestias deserunt fuga commodi ea!</li>
        <li>Quo cupiditate quasi aliquid quia repellat sed velit hic voluptas!</li>
        <li>Velit sunt dolore tempore consequuntur, iste vitae saepe ad aspernatur?</li>
        <li>Culpa, non. Explicabo amet sequi illo magni, iste dolorum! Sapiente!</li>
        <li>Mollitia exercitationem harum veniam at accusamus, quaerat commodi sint obcaecati!</li>
        <li>Consequuntur voluptate est repudiandae amet rerum aut beatae reprehenderit corporis?</li>
        <li>Quasi commodi aperiam doloremque odit. Amet cupiditate similique magnam rerum?</li>
        <li>Accusamus enim modi officia odit nesciunt vitae commodi sint optio!</li>
        <li>Minima adipisci, recusandae autem harum odit placeat corrupti nisi! Rem!</li>
        <li>Asperiores, deleniti. Ipsam tenetur, reiciendis possimus vero corporis alias iure?</li>
        <li>Fuga unde, dicta fugit saepe ex itaque quod molestiae labore?</li>
        <li>Nemo deserunt ipsam numquam consequatur sunt? Delectus, dolor. Libero, excepturi.</li>
      </ul>
    </div>
  )
}
